Repository radical-doubting/anikultura-backend, pull requests merged in 2022-09, with the labels that each got.

#96 [Chore] Add Prometheus support for insights
  .dockerignore
  .gitignore
  Dockerfile
  Procfile
  README.md
  agent-config.yml
  app/Collectors/BatchCollector.php
  app/Collectors/CropCollector.php
  app/Collectors/FarmerCollector.php
  app/Collectors/FarmlandCollector.php
  app/Collectors/SiteCollector.php
  app/Helpers/InsightsHelper.php
  app/Observers/Batch/BatchObserver.php
  app/Observers/Batch/BatchSeedAllocationObserver.php
  app/Observers/Crop/CropObserver.php
  app/Observers/FarmerReport/FarmerReportObserver.php
  app/Observers/Farmland/FarmlandObserver.php
  app/Observers/Site/MunicityObserver.php
  app/Observers/Site/ProvinceObserver.php
  app/Observers/Site/RegionObserver.php
  app/Orchid/Screens/Batch/BatchSeedAllocationEditScreen.php
  app/Providers/AppServiceProvider.php
  app/Traits/AsInsightSender.php
  composer.json
  composer.lock
  config/app.php
  config/prometheus.php
  docker-compose.yml
  grafana/batches-dashboard.json
  grafana/crops-profit-dashboard.json
  grafana/farmer-reports-dashboard.json
  grafana/farmers-dashboard.json
  grafana/farmlands-dashboard.json
  grafana/seed-allocations-dashboard.json
  grafana/sites-dashboard.json
  prometheus-config.yml
  setup-agent.sh
Labels: enhancement, chore

#95 [ANI-73] Preferred language option
  app/Http/Controllers/LanguageController.php
  app/Http/Kernel.php
  app/Http/Middleware/Languages.php
  app/Orchid/Layouts/Batch/BatchListLayout.php
  app/Orchid/Layouts/Batch/BatchSeedAllocationListLayout.php
  app/Orchid/Layouts/Crop/CropEditBasicLayout.php
  app/Orchid/Layouts/Crop/CropEditGrowthLayout.php
  app/Orchid/Layouts/Crop/CropListLayout.php
  app/Orchid/Layouts/Farmer/FarmerListLayout.php
  app/Orchid/Layouts/Farmland/FarmlandListLayout.php
  app/Orchid/Layouts/Site/Municity/MunicityEditLayout.php
  app/Orchid/Layouts/Site/Province/ProvinceEditLayout.php
  app/Orchid/Layouts/User/UserListLayout.php
  app/Orchid/PlatformProvider.php
  app/Orchid/Screens/AnikulturaListScreen.php
  app/Orchid/Screens/Batch/BatchEditScreen.php
  app/Orchid/Screens/Batch/BatchListScreen.php
  app/Orchid/Screens/Batch/BatchSeedAllocationEditScreen.php
  app/Orchid/Screens/BigBrother/BigBrotherEditScreen.php
  app/Orchid/Screens/BigBrother/BigBrotherListScreen.php
  app/Orchid/Screens/Crop/CropListScreen.php
  app/Orchid/Screens/Farmer/FarmerEditScreen.php
  app/Orchid/Screens/Farmer/FarmerListScreen.php
  app/Orchid/Screens/FarmerReport/FarmerReportEditScreen.php
  app/Orchid/Screens/FarmerReport/FarmerReportListScreen.php
  app/Orchid/Screens/Farmland/FarmlandEditScreen.php
  app/Orchid/Screens/Farmland/FarmlandListScreen.php
  app/Orchid/Screens/PlatformScreen.php
  app/Orchid/Screens/Role/RoleEditScreen.php
  config/languages.php
  resources/lang/fil_PH.json
  resources/views/brand/footer.blade.php
  resources/views/vendor/platform/partials/welcome.blade.php
  routes/platform.php
  routes/web.php
Labels: enhancement

#103 [Test] Add PestPHP
  .env.example
  .github/actions/integration/action.yml
  .github/workflows/analyze.yml
  app/Actions/Site/Municity/CreateMunicity.php
  app/Actions/Site/Municity/DeleteMunicity.php
  app/Actions/Site/Province/DeleteProvince.php
  app/Actions/Site/Region/DeleteRegion.php
  composer.json
  composer.lock
  config/sluggable.php
  tests/Feature/Actions/Site/Municity/CreateMunicityTest.php
  tests/Feature/Actions/Site/Municity/DeleteMunicityTest.php
  tests/Feature/Actions/Site/Province/CreateProvinceTest.php
  tests/Feature/Actions/Site/Province/DeleteProvinceTest.php
  tests/Feature/Actions/Site/Region/CreateRegionTest.php
  tests/Feature/Actions/Site/Region/DeleteRegionTest.php
  tests/Pest.php
  tests/Unit/Actions/Site/Municity/CreateMunicityTest.php
  tests/Unit/Actions/Site/Municity/DeleteMunicityTest.php
  tests/Unit/Actions/Site/Province/CreateProvinceTest.php
  tests/Unit/Actions/Site/Province/DeleteProvinceTest.php
  tests/Unit/Actions/Site/Region/CreateRegionTest.php
  tests/Unit/Actions/Site/Region/DeleteRegionTest.php
Labels: enhancement

#106 [Chore] Update readme
  README.md
  docs/img/ani-logo.png
Labels: chore

#112 [Feature] Add headless mode
  .env.example
  .github/workflows/pr-title-check.yml
  app/Anikultura.php
  app/Facades/Anikultura.php
  app/Providers/AppServiceProvider.php
  app/Providers/PlatformFoundationServiceProvider.php
  app/Providers/PlatformProvider.php
  composer.json
  composer.lock
  config/anikultura.php
  config/app.php
  config/platform.php
  phpunit.xml
  routes/web.php
  tests/Feature/HeadlessTest.php
  tests/Pest.php
Labels: enhancement

#118 [Test] More farmer tests
  app/Actions/Farmer/CreateFarmer.php
  app/Actions/Farmer/CreateFarmerAddress.php
  app/Actions/Farmer/CreateFarmerPreference.php
  app/Actions/Farmer/CreateFarmerProfile.php
  app/Actions/Farmer/DeleteFarmer.php
  app/Models/Farmer/FarmerAddress.php
  database/migrations/2021_06_06_155928_create_farmer_reports_table.php
  database/seeders/Admin/AdminSeeder.php
  database/seeders/BigBrother/BigBrotherSeeder.php
  database/seeders/Crop/CropSeeder.php
  database/seeders/DatabaseSeeder.php
  database/seeders/Farmer/FarmerProfileSeeder.php
  database/seeders/Farmer/FarmerSeeder.php
  database/seeders/Farmland/FarmlandSeeder.php
  database/seeders/Site/SiteSeeder.php
  tests/Feature/Actions/Farmer/CreateFarmerAddressTest.php
  tests/Feature/Actions/Farmer/CreateFarmerPreferenceTest.php
  tests/Feature/Actions/Farmer/CreateFarmerProfileTest.php
  tests/Feature/Actions/Farmer/CreateFarmerTest.php
  tests/Feature/Actions/Farmer/DeleteFarmerTest.php
  tests/Feature/Orchid/Screens/LoginScreenTest.php
  tests/Feature/Orchid/Screens/PlatformScreenTest.php
  tests/Feature/Orchid/Screens/Site/Municity/MunicityEditScreenTest.php
  tests/Feature/Orchid/Screens/Site/Municity/MunicityListScreenTest.php
  tests/Feature/Orchid/Screens/Site/Province/ProvinceEditScreenTest.php
  tests/Feature/Orchid/Screens/Site/Province/ProvinceListScreenTest.php
  tests/Feature/Orchid/Screens/Site/Region/RegionEditScreenTest.php
  tests/Feature/Orchid/Screens/Site/Region/RegionListScreenTest.php
  tests/Pest.php
Labels: tests

#120 [Chore] Polish presenters and update logo
  app/Models/Farmer/Farmer.php
  app/Models/User.php
  app/Orchid/Layouts/Farmer/FarmerListLayout.php
  app/Orchid/Layouts/User/UserListLayout.php
  app/Orchid/Presenters/FarmerPresenter.php
  app/Orchid/Presenters/UserPresenter.php
  app/Orchid/Screens/User/UserListScreen.php
  public/img/ani-logo-color.png
  public/img/ani-logo-icon.png
  public/img/ani-logo-white.png
  resources/views/brand/header.blade.php
  resources/views/vendor/platform/partials/welcome.blade.php
Labels: chore

#117 [ANI-41] Farmer report notification
  app/Actions/FarmerReport/CreateFarmerReport.php
  app/Actions/User/SwitchLanguage.php
  app/Events/ReadyForHarvestEvent.php
  app/Http/Middleware/UpdateLocale.php
  app/Listeners/SendReadyForHarvestListener.php
  app/Models/Notification/Notification.php
  app/Models/User.php
  app/Notifications/SendReadyForHarvestNotification.php
  app/Providers/EventServiceProvider.php
  composer.lock
  database/migrations/2022_09_25_121649_add_locale_column_to_users_table.php
  resources/lang/fil_PH.json
Labels: enhancement

#122 [Chore] Add Prometheus password configuration and Cebuano language validation
  .env.example
  app/Actions/Farmer/Api/UpdateFarmerLanguage.php
  config/prometheus.php
  tests/Feature/Actions/Farmer/Api/UpdateFarmerLanguageTest.php
Labels: chore

#126 [Chore] Add logging
  Makefile
  README.md
  agent-config.yml
  app/Actions/Authentication/Api/LoginFarmer.php
  app/Actions/FarmerReport/Api/SubmitFarmerReport.php
  app/Models/Admin/AdminProfile.php
  app/Models/Batch/Batch.php
  app/Models/Batch/BatchSeedAllocation.php
  app/Models/BigBrother/BigBrotherProfile.php
  app/Models/Crop/Crop.php
  app/Models/Farmer/FarmerAddress.php
  app/Models/Farmer/FarmerPreference.php
  app/Models/Farmer/FarmerProfile.php
  app/Models/FarmerReport/FarmerReport.php
  app/Models/Farmland/Farmland.php
  app/Models/Site/Municity.php
  app/Models/Site/Province.php
  app/Models/Site/Region.php
  app/Models/User.php
  app/Observers/LoggingObserver.php
  app/Traits/Loggable.php
  config/logging.php
  docker-compose.yml
  loki-config.yml
  phpunit-sqlite.xml
  phpunit.xml
  prometheus-config.yml
  tests/Feature/Traits/LoggableTest.php
  tests/Pest.php
Labels: chore

#132 [Test] Improve site screen tests
  app/Actions/Site/Municity/CreateMunicity.php
  app/Actions/Site/Municity/DeleteMunicity.php
  tests/Feature/Orchid/Screens/Site/Municity/MunicityEditScreenTest.php
  tests/Feature/Orchid/Screens/Site/Province/ProvinceEditScreenTest.php
  tests/Feature/Orchid/Screens/Site/Region/RegionEditScreenTest.php
Labels: tests
