Repository radical-doubting/anikultura-backend, pull requests merged in 2022-11, with the labels that each got.

#203 [Feature] Add production Dockerfile
  .dockerignore
  Dockerfile
Labels: enhancement

#205 [Chore] Add codecov config and fix tests
  codecov.yml
  tests/Feature/Orchid/Screens/User/Admin/AdminEditScreenTest.php
Labels: chore

#208 [Feature] Add assignment information to farmer edit screen
  app/Orchid/Layouts/User/Farmer/FarmerListBatchLayout.php
  app/Orchid/Layouts/User/Farmer/FarmerListFarmlandLayout.php
  app/Orchid/Screens/User/Farmer/FarmerEditScreen.php
  codecov.yml
Labels: enhancement

#209 [Feature] Update big brother functionality
  app/Actions/Batch/CreateBatch.php
  app/Actions/Batch/DeleteBatch.php
  app/Actions/FarmerReport/CreateFarmerReport.php
  app/Actions/FarmerReport/DeleteFarmerReport.php
  app/Actions/Farmland/CreateFarmland.php
  app/Actions/Farmland/DeleteFarmland.php
  app/Actions/User/Farmer/CreateFarmer.php
  app/Actions/User/Farmer/DeleteFarmer.php
  app/Models/Batch/Batch.php
  app/Models/FarmerReport/FarmerReport.php
  app/Models/Farmland/Farmland.php
  app/Models/User/Farmer/Farmer.php
  app/Models/User/User.php
  app/Orchid/Layouts/Batch/BatchEditMemberLayout.php
  app/Orchid/Layouts/Batch/BatchListLayout.php
  app/Orchid/Layouts/Batch/BatchSeedAllocationListLayout.php
  app/Orchid/Layouts/FarmerReport/FarmerReportEditVerificationLayout.php
  app/Orchid/Layouts/Farmland/FarmlandEditBasicLayout.php
  app/Orchid/Layouts/Farmland/FarmlandListLayout.php
  app/Orchid/Layouts/User/Farmer/FarmerEditAssignmentLayout.php
  app/Orchid/Screens/AnikulturaEditScreen.php
  app/Orchid/Screens/Batch/BatchEditScreen.php
  app/Orchid/Screens/Batch/BatchListScreen.php
  app/Orchid/Screens/FarmerReport/FarmerReportEditScreen.php
  app/Orchid/Screens/FarmerReport/FarmerReportListScreen.php
  app/Orchid/Screens/Farmland/FarmlandEditScreen.php
  app/Orchid/Screens/Farmland/FarmlandListScreen.php
  app/Orchid/Screens/User/Farmer/FarmerEditScreen.php
  app/Orchid/Screens/User/Farmer/FarmerListScreen.php
  app/Policies/BatchPolicy.php
  app/Policies/FarmerPolicy.php
  app/Policies/FarmerReportPolicy.php
  app/Policies/FarmlandPolicy.php
  app/Providers/AuthServiceProvider.php
  app/Providers/PlatformProvider.php
  app/Traits/AsOrchidAction.php
  database/migrations/2022_11_05_090757_create_batch_big_brothers_table.php
  database/seeders/User/RoleSeeder.php
  tests/Feature/Orchid/Screens/Batch/BatchEditScreenTest.php
  tests/Feature/Orchid/Screens/Batch/BatchListScreenTest.php
  tests/Feature/Orchid/Screens/FarmerReport/FarmerReportEditScreenTest.php
  tests/Feature/Orchid/Screens/FarmerReport/FarmerReportListScreenTest.php
  tests/Feature/Orchid/Screens/Farmland/FarmlandEditScreenTest.php
  tests/Feature/Orchid/Screens/Farmland/FarmlandListScreenTest.php
  tests/Feature/Orchid/Screens/User/Farmer/FarmerEditScreenTest.php
  tests/Feature/Orchid/Screens/User/Farmer/FarmerListScreenTest.php
Labels: enhancement

#214 [Test] Add insight observer tests
  app/Models/Batch/Batch.php
  app/Models/Batch/BatchSeedAllocation.php
  app/Models/FarmerReport/FarmerReport.php
  app/Models/Farmland/Farmland.php
  app/Models/Site/Municity.php
  app/Models/Site/Province.php
  app/Observers/Batch/BatchInsightObserver.php
  tests/Feature/Observers/Batch/BatchInsightObserverTest.php
  tests/Feature/Observers/Batch/BatchSeedAllocationInsightObserverTest.php
  tests/Feature/Observers/Crop/CropInsightObserverTest.php
  tests/Feature/Observers/FarmerReport/FarmerReportHarvestedObserverTest.php
  tests/Feature/Observers/FarmerReport/FarmerReportInsightObserverTest.php
  tests/Feature/Observers/Farmland/FarmlandInsightObserverTest.php
  tests/Feature/Observers/Site/MunicityInsightObserverTest.php
  tests/Feature/Observers/Site/ProvinceInsightObserverTest.php
  tests/Feature/Observers/Site/RegionInsightObserverTest.php
  tests/Pest.php
Labels: tests

#216 [Chore] Upgrade dependencies
  composer.json
  composer.lock
  public/vendor/orchid/css/orchid.css
  public/vendor/orchid/css/orchid.rtl.css
  public/vendor/orchid/css/orchid.rtl.css.map
  public/vendor/orchid/js/orchid.js
  public/vendor/orchid/js/orchid.js.map
  public/vendor/orchid/js/vendor.js
  public/vendor/orchid/js/vendor.js.map
  public/vendor/orchid/mix-manifest.json
Labels: chore

#220 [Fix] Updated Translations for Admin Management
  package-lock.json
  resources/lang/fil_PH.json
Labels: fix
