Repository radical-doubting/anikultura-backend, pull requests merged in 2022-10, with the labels that each got.

#140 [Feature] Add insights button and list screen enhancements
  .env.example
  app/Helpers/InsightsHelper.php
  app/Models/User/Role.php
  app/Orchid/Filters/RoleFilter.php
  app/Orchid/Filters/User/UserNameFilter.php
  app/Orchid/Layouts/Role/RoleListLayout.php
  app/Orchid/Layouts/User/BigBrother/BigBrotherFiltersLayout.php
  app/Orchid/Layouts/User/BigBrother/BigBrotherListLayout.php
  app/Orchid/Layouts/User/Farmer/FarmerFiltersLayout.php
  app/Orchid/Layouts/User/Farmer/FarmerListLayout.php
  app/Orchid/Layouts/User/UserRoleLayout.php
  app/Orchid/Screens/Batch/BatchListScreen.php
  app/Orchid/Screens/Crop/CropListScreen.php
  app/Orchid/Screens/FarmerReport/FarmerReportListScreen.php
  app/Orchid/Screens/Farmland/FarmlandListScreen.php
  app/Orchid/Screens/Role/RoleEditScreen.php
  app/Orchid/Screens/Role/RoleListScreen.php
  app/Orchid/Screens/Site/Municity/MunicityListScreen.php
  app/Orchid/Screens/Site/Province/ProvinceListScreen.php
  app/Orchid/Screens/Site/Region/RegionListScreen.php
  app/Orchid/Screens/User/BigBrother/BigBrotherListScreen.php
  app/Orchid/Screens/User/Farmer/FarmerListScreen.php
  config/anikultura.php
  database/seeders/User/Admin/AdminSeeder.php
  database/seeders/User/BigBrother/BigBrotherSeeder.php
  database/seeders/User/RoleSeeder.php
  resources/lang/fil_PH.json
  resources/views/vendor/platform/partials/welcome.blade.php
Labels: enhancement

#142 [Chore] Add codecov
  .github/workflows/coverage.yml
  database/migrations/2022_01_17_135656_add_slug_columns_for_insights.php
Labels: enhancement

#143 [Chore] Add codecov badge
  README.md
Labels: enhancement

#144 [Fix] Fix delete batches and add configurable edit screen methods
  app/Orchid/Screens/AnikulturaEditScreen.php
  app/Orchid/Screens/Batch/BatchEditScreen.php
Labels: enhancement, fix

#146 [Chore] Remove unused helpers
  app/Helpers/MetricPropertyHelper.php
  app/Helpers/PostgresHelper.php
Labels: chore

#148 [Test] Add more screen tests
  app/Actions/Batch/CreateBatchSeedAllocation.php
  app/Models/Batch/Batch.php
  app/Orchid/Layouts/Farmland/FarmlandEditAddressLayout.php
  app/Orchid/Layouts/Farmland/FarmlandEditAppStatusLayout.php
  database/factories/Batch/BatchSeedAllocationFactory.php
  database/factories/Crop/CropFactory.php
  database/factories/FarmerReport/FarmerReportFactory.php
  database/factories/Farmland/FarmlandFactory.php
  database/factories/User/BigBrother/BigBrotherProfileFactory.php
  database/seeders/FarmerReport/FarmerReportSeeder.php
  database/seeders/Farmland/FarmlandSeeder.php
  tests/Feature/Orchid/Screens/Batch/BatchEditScreenTest.php
  tests/Feature/Orchid/Screens/Batch/BatchListScreenTest.php
  tests/Feature/Orchid/Screens/Batch/BatchSeedAllocationEditScreenTest.php
  tests/Feature/Orchid/Screens/Crop/CropEditScreenTest.php
  tests/Feature/Orchid/Screens/Crop/CropListScreenTest.php
  tests/Feature/Orchid/Screens/FarmerReport/FarmerReportEditScreenTest.php
  tests/Feature/Orchid/Screens/FarmerReport/FarmerReportListScreenTest.php
  tests/Feature/Orchid/Screens/Farmland/FarmlandEditScreenTest.php
  tests/Feature/Orchid/Screens/Farmland/FarmlandListScreenTest.php
Labels: enhancement, tests

#155 [Feature] Make insight sender handle decrements
  app/Traits/AsInsightSender.php
Labels: enhancement

#163 [Fix] Remove sensitive server headers
  docker/sail/7.4/php.ini
  docker/sail/8.0/php.ini
  docker/sail/8.1/php.ini
  public/.user.ini
Labels: fix

#166 [Feature] Change region name to dropdown
  app/Actions/Site/Municity/CreateMunicity.php
  app/Models/Site/Municity.php
  app/Models/Site/Region.php
  app/Orchid/Layouts/Site/Municity/MunicityEditLayout.php
  tests/Feature/Orchid/Screens/Site/Municity/MunicityEditScreenTest.php
Labels: enhancement

#164 [Fix] Fix validation rules
  app/Actions/Batch/CreateBatch.php
  app/Actions/Crop/CreateCrop.php
  app/Actions/FarmerReport/Api/SubmitFarmerReport.php
  app/Actions/Farmland/CreateFarmland.php
  app/Actions/Site/Municity/CreateMunicity.php
  app/Actions/Site/Province/CreateProvince.php
  app/Actions/Site/Region/CreateRegion.php
  app/Actions/User/Admin/CreateAdmin.php
  app/Actions/User/BigBrother/CreateBigBrother.php
  app/Actions/User/Farmer/CreateFarmer.php
  app/Helpers/PasswordRuleHelper.php
  app/Http/Resources/FarmerReport/FarmerReportResource.php
  app/Models/Batch/Batch.php
  app/Models/FarmerReport/FarmerReport.php
  app/Models/FarmerReport/FarmerReportStatus.php
  app/Orchid/Layouts/Batch/BatchEditFarmlandLayout.php
  app/Orchid/Layouts/Batch/BatchEditLayout.php
  app/Orchid/Layouts/Crop/CropEditBasicLayout.php
  app/Orchid/Layouts/Crop/CropEditGrowthLayout.php
  app/Orchid/Layouts/FarmerReport/FarmerReportEditInfoLayout.php
  app/Orchid/Layouts/FarmerReport/FarmerReportEditVerificationLayout.php
  app/Orchid/Layouts/FarmerReport/FarmerReportListLayout.php
  app/Orchid/Layouts/Farmland/FarmlandListLayout.php
  app/Orchid/Layouts/User/Admin/AdminEditPasswordLayout.php
  app/Orchid/Layouts/User/BigBrother/BigBrotherEditAccountLayout.php
  app/Orchid/Layouts/User/BigBrother/BigBrotherEditPasswordLayout.php
  app/Orchid/Layouts/User/Farmer/FarmerEditAccountLayout.php
  app/Orchid/Layouts/User/Farmer/FarmerEditPasswordLayout.php
  app/Orchid/Layouts/User/Farmer/FarmerEditSalaryLayout.php
  app/Orchid/Screens/Batch/BatchEditScreen.php
  app/Orchid/Screens/FarmerReport/FarmerReportEditScreen.php
  app/Orchid/Screens/User/Admin/AdminEditScreen.php
  app/Orchid/Screens/User/BigBrother/BigBrotherEditScreen.php
  app/Orchid/Screens/User/Farmer/FarmerEditScreen.php
  app/Providers/AppServiceProvider.php
  app/Traits/AsOrchidAction.php
  database/factories/FarmerReport/FarmerReportFactory.php
  database/factories/User/Farmer/FarmerProfileFactory.php
  database/migrations/2022_10_11_123153_create_farmer_report_statuses_table.php
  database/migrations/2022_10_11_123944_add_farmer_report_status_to_farmer_reports_table.php
  database/seeders/FarmerReport/FarmerReportSeeder.php
  database/seeders/FarmerReport/FarmerReportStatusSeeder.php
  resources/lang/en/validation.php
  resources/lang/fil_PH/validation.php
  tests/Feature/Actions/Crop/Api/RetrieveCurrentSeedStageTest.php
  tests/Feature/Actions/Crop/Api/RetrieveNextSeedStageTest.php
  tests/Feature/Actions/FarmerReport/Api/RetrieveFarmerSubmittedReportsTest.php
  tests/Feature/Actions/FarmerReport/Api/SubmitFarmerReportTest.php
  tests/Feature/Orchid/Screens/FarmerReport/FarmerReportEditScreenTest.php
  tests/Feature/Orchid/Screens/FarmerReport/FarmerReportListScreenTest.php
  tests/Feature/Orchid/Screens/User/Admin/AdminEditScreenTest.php
  tests/Feature/Orchid/Screens/User/BigBrother/BigBrotherEditScreenTest.php
  tests/Feature/Orchid/Screens/User/Farmer/FarmerEditScreenTest.php
Labels: fix

#173 [Fix] Make farmland block be seen on edit screen only
  app/Orchid/Screens/Batch/BatchEditScreen.php
Labels: fix

#174 [Fix] Make farmland list layout handle null batches
  app/Orchid/Layouts/Farmland/FarmlandListLayout.php
Labels: fix

#177 [Fix] Make farmland full name handle null batches
  app/Models/Farmland/Farmland.php
Labels: fix

#180 [Fix] Optimize update password layout
  app/Actions/User/Admin/CreateAdmin.php
  app/Actions/User/BigBrother/CreateBigBrother.php
  app/Actions/User/ChangePassword.php
  app/Actions/User/EditUserProfile.php
  app/Actions/User/Farmer/CreateFarmer.php
  app/Orchid/Layouts/User/ProfileUserEditLayout.php
  app/Orchid/Screens/User/UserProfileScreen.php
  tests/Feature/Orchid/Screens/User/UserProfileScreenTest.php
Labels: fix

#181 [Fix] Fix farmland hectares input number range
  app/Orchid/Layouts/Farmland/FarmlandEditBasicLayout.php
Labels: fix

#189 [Fix] Fix relational integrity and add friendly error toasts
  app/Actions/Batch/DeleteBatch.php
  app/Actions/Crop/DeleteCrop.php
  app/Actions/Farmland/DeleteFarmland.php
  app/Actions/Site/Municity/DeleteMunicity.php
  app/Actions/Site/Province/DeleteProvince.php
  app/Actions/Site/Region/DeleteRegion.php
  app/Actions/User/Admin/DeleteAdmin.php
  app/Actions/User/BigBrother/DeleteBigBrother.php
  app/Actions/User/Farmer/DeleteFarmer.php
  app/Helpers/ToastHelper.php
  app/Models/User/Farmer/FarmerApplicationVerification.php
  app/Orchid/Screens/User/Role/RoleEditScreen.php
  database/migrations/2021_05_26_093919_create_provinces_table.php
  database/migrations/2021_05_26_100125_create_municities_table.php
  database/migrations/2021_06_02_024411_create_application_verifications_table.php
  database/migrations/2021_06_06_034000_create_farmer_addresses_table.php
  database/migrations/2021_06_06_043248_create_farmlands_table.php
  database/migrations/2021_06_06_155928_create_farmer_reports_table.php
  resources/lang/fil_PH.json
Labels: fix

#196 [Fix] Fix farmland batch integrity and delete user bug
  app/Actions/Batch/CreateBatch.php
  app/Actions/Crop/Api/RetrieveCurrentSeedStage.php
  app/Actions/Farmland/CreateFarmland.php
  app/Actions/User/Admin/DeleteAdmin.php
  app/Actions/User/BigBrother/DeleteBigBrother.php
  app/Actions/User/Farmer/DeleteFarmer.php
  app/Models/Farmland/Farmland.php
  app/Models/User/Farmer/Farmer.php
  app/Orchid/Layouts/Batch/BatchEditMemberLayout.php
  app/Orchid/Layouts/Batch/BatchEditSiteLayout.php
  app/Orchid/Layouts/Batch/BatchListLayout.php
  app/Orchid/Layouts/FarmerReport/FarmerReportEditInfoLayout.php
  app/Orchid/Layouts/Farmland/FarmlandEditMemberLayout.php
  app/Orchid/Layouts/Farmland/FarmlandEditMemberListener.php
  app/Orchid/Screens/Batch/BatchEditScreen.php
  app/Orchid/Screens/Farmland/FarmlandEditScreen.php
  database/seeders/Farmland/FarmlandSeeder.php
  tests/Feature/Orchid/Screens/Farmland/FarmlandEditScreenTest.php
Labels: fix

#197 [Fix] Remove add farmer report
  app/Orchid/Screens/FarmerReport/FarmerReportListScreen.php
  routes/platform/farmer_reports.php
  tests/Feature/Orchid/Screens/FarmerReport/FarmerReportEditScreenTest.php
Labels: fix

#200 [Fix] Fix batch seed allocation
  app/Actions/Batch/CreateBatchSeedAllocation.php
  app/Orchid/Layouts/Batch/BatchSeedAllocationEditLayout.php
  app/Orchid/Screens/Batch/BatchEditScreen.php
  app/Orchid/Screens/Batch/BatchSeedAllocationEditScreen.php
  tests/Feature/Orchid/Screens/Batch/BatchSeedAllocationEditScreenTest.php
Labels: fix
